package com.protsaha.brightfuture.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

// The @Data annotation from Lombok automatically generates getters, setters,
// toString(), equals(), and hashCode() methods for all fields.
@Data
@Document(collection = "staff")
public class Staff {

    // The @Id annotation marks this field as the unique identifier for the document
    // The field name is updated to 'staffId' to match the JSON reference.
    @Id
    @Field("staffId")
    private String staffId;

    // This field will have a corresponding `getPersonalDetails()` getter
    // and `setPersonalDetails()` setter generated by Lombok.
    private PersonalDetails personalDetails;

    private String position;

    private String department;

    private double salary;

    // New fields added to resolve the errors from the screenshot
    private AadharInfo aadharInfo;

    private Address address;

    private Employment employment;

    // You can add more fields as needed for your staff model
}
